apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: demo.app
spec:
  selector:
    matchLabels:
      app: demo.app
  replicas: 2
  template:
    metadata:
      labels:
        app: demo.app
    spec:
      containers:
      - name: 241099261431.dkr.ecr.us-east-1.amazonaws.com/jesse-ccits/demo-app:latest
        image: 
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: demo.service
spec:
  selector:
    app: demo.app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000